first commit

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -39,3 +39,89 @@ pipeline{
         }
     }
 }
+
+pipeline{
+    agent any 
+    environment {
+        IMAGE_NAME ="Bhagya0603/frontend-app"
+        IMAGE_TAG ="${BUILD_NUMBER}"
+        APP_SERVER ="3.110.164.144"
+    }
+    stages{
+
+        stage('Checkout'){
+
+            steps{
+                git branch:main ,
+                url: 'https://github.com/Bhagya0603/Jenkins-webapp1.git'
+            }
+        }
+        stage('Build Docker Image'){
+            steps {
+
+                sh '''
+                docker build -f docker/dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
+                '''
+            }
+        }
+        stage ('Docker login') {
+            steps {
+                withCredential([
+                    usernamePassword(
+                        credintialsId:'Dockercred'
+                        usernameVariable: 'DOCKER_USER'
+                        passwordVariable: 'DOCKER-PASS'
+
+                    )
+                ]) {
+                    sh '''
+                    echo $DOCKER_PASS | docker login \
+                    -u $DOCKER_USER \
+                    --password-stdin
+                    '''
+                }
+            }
+        }
+        stage('push Image'){
+            steps{
+                sh '''
+                docker push $IMAGE_NAME:$IMAGE_TAG
+                docker tag \
+                $IMAGE_NAME:$IMAGE_TAG \
+                $IMAGE_NAME:latest
+                docker push $IMAGE_NAME:latest
+                '''
+            }
+        }
+        stage('Deploy to App Server'){
+            steps{
+                sh"""
+                ssh ubuntu@$APP_SERVER '
+                docker pull $IMAGE_NAME:latest
+                docker stop frontend || true
+                docker rm frontend || true
+                docker run -d \
+                --name frontend \
+                -p 80:80 \
+                $IMAGE_NAME:latest
+                '
+                """
+            }
+        }
+        post {
+            success{
+                echo "Deployment Successful"
+            }
+            failure {
+                echo "Deployment Failed"
+
+            }
+            }
+        }
+        
+            
+            
+
+
+            }
+        
